### ISSUE TITLE
Add egghead video embed

### ISSUE THREAD

**Issue by zacjones93** [laurosilvacom/awesomecheatsheets#8]
We have the ability to add videos inline as embeds by appending `/embed` to the end of the lesson url. It could be cool to add them to the individual notes page. 

You can see an example of how [Gatsby does this with their docs here](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/shared/egghead-embed.js).

and this is how it looks ([link](https://www.gatsbyjs.org/docs/themes/building-themes/)): 
![Image 2020-01-28 at 11 45 26 AM](https://user-images.githubusercontent.com/6188161/73285202-afacff80-41c3-11ea-8290-dbb7cdd9b532.png)

**Comment by laurosilvacom** [comment]
I think this a great idea! Do you want to work on this @zacjones93?

**Comment by theianjones** [comment]
I've recently done this one my blog ([github commit link](https://github.com/theianjones/blog/commit/5649fcbe4f8b740bb3e5ec86ae4feae7e3e0678e)). This uses [gatsby-remark-embedder (gatsby docs link)](https://www.gatsbyjs.org/packages/gatsby-remark-embedder/) and a [custom transformer](https://github.com/theianjones/blog/commit/5649fcbe4f8b740bb3e5ec86ae4feae7e3e0678e#diff-7b9b3a039f22643f1bd732b78551c17e) for egghead lessons specifically (I took it from @kentcdodds blog).  

Then all you need to do is place an egghead lesson url (no `/embed` needed).

**Comment by nikkilr88** [comment]
I would like to give this one a try!

**Comment by laurosilvacom** [comment]
@nikkilr88 go for it! Reach out if you need any help.
